BredaUniversityResearch/MSPChallenge-Client

Assets/Scenes/MSP2050.unity
Fixed the tooltip field of the button with the text "Pause"
=> MSP-3458 Bugfix: Pause button tooltip shows 'Play'

Assets/Scripts/Interface/Tooltip/AddTooltip.cs, Assets/Scripts/Interface/Tooltip/Tooltip.cs, Assets/Scripts/Interface/Tooltip/TooltipManager.cs
hack. make sure the tooltip for drop-down is rendered on-top
=> hack. make sure the tooltip for drop-down is rendered on-top

Assets/Prefabs/Windows/OptionsWindow/OptionsWindow.prefab, Assets/Scripts/Interface/Options/Options.cs, Assets/Scripts/Utility/ApplicationBuildIdentifier.cs
- Removed from Scene and commented from code "ApiEndpoint Info".
- Propagated version number in parent prefab as temporary solution to the issue presented by the User Story.
- Used correct Text to display version.
Currently working (in the scope of this user story) to implement working build versioning (Git/Ucb)
=> MSP-3655: Fix three problems with Main Menu variables

Assets/Packages.meta, Assets/Prefabs/Windows/OptionsWindow/OptionsWindow.prefab, Assets/Scenes/LoginScene.unity, Assets/Scripts/Interface/Options/Options.cs, Assets/Scripts/Networking/Server.cs
Removed API Endpoint Url from options menu in login screen and fixed it in game.
=> MSP-3655 Fix three problems with Main Menu variables

Assets/Resources/ValueConversion/ConversionCollection.asset, Assets/Resources/ValueConversion/Money.asset, Assets/Resources/ValueConversion/Points.asset, Assets/Resources/ValueConversion/SquareKilometres.asset, Assets/Resources/ValueConversion/SquareKilometres.asset.meta, Assets/Resources/ValueConversion/Tonnes.asset, Assets/Resources/ValueConversion/TonnesPerSquareKilometer.asset, Assets/Resources/ValueConversion/Watts.asset, Assets/Scripts/Constraints/ConstraintManager.cs, Assets/Scripts/Editor/Interface/ValueConversion/ValueConversionUnitEditor.cs, Assets/Scripts/Interface/Plan Wizard/PlanWizard.cs, Assets/Scripts/Interface/ValueConversion/ValueConversionCollection.cs, Assets/Scripts/Interface/ValueConversion/ValueConversionUnit.cs, Assets/Scripts/KPI/CountryKPICollectionGeometry.cs, Assets/Scripts/KPI/KPIManager.cs
Added KM2 and t/KM2 units, updated 0 values to used base unit format instead. Made planwizard do an issue check if layers are removed.
=> MSP 3709 3767,  KM2 display & planwizard layer check

Assets/Prefabs/Windows/KPIWindows/Groups/KPI Group Bar (Ecology).prefab, Assets/Prefabs/Windows/KPIWindows/Groups/KPI Group Bar (Energy).prefab, Assets/Prefabs/Windows/KPIWindows/KPI Bar Child.prefab, Assets/Prefabs/Windows/KPIWindows/KPI Bar.prefab, Assets/Prefabs/Windows/ObjectivesMonitorWindow/Objective.prefab, Assets/Prefabs/Windows/PlansMonitorWindow/PlanDetails/Distribution Elements/Ecology/Distribution Group (Ecology).prefab, Assets/Prefabs/Windows/PlansMonitorWindow/PlanDetails/Distribution Elements/Energy/Distribution Group (Energy).prefab, Assets/Prefabs/Windows/PlansMonitorWindow/PlanDetails/Distribution Elements/Shipping/Distribution Group (Shipping).prefab, Assets/Prefabs/Windows/PlansMonitorWindow/PlanDetails/Distribution Elements/Shipping/Distribution Item (Shipping).prefab
MSP-3704 & MSP-3631: fixed double toggle behaviour on bars (KPI, objective, distribution)
=> MSP-3704 & MSP-3631: fixed double toggle behaviour on bars (KPI, objective, distribution)

Assets/Scripts/ImpactTool/WikiLinkBrowserHandler.cs, Assets/Scripts/Interface/Active Layers/ActiveLayerWindow.cs, Assets/Scripts/Interface/Active Plans Window/ActivePlanLayerType.cs, Assets/Scripts/Interface/GameMenu/GameMenu.cs, Assets/Scripts/Interface/Menu Bar/Toggles/Base/MenuBarToggle.cs, Assets/Scripts/Interface/PropertiesWindow.cs, Assets/Scripts/Interface/WebViewWindow.cs
Made the knowledge base window always open at the same size and position. Old code was left in commented, in case this behaviour needs to be altered later.
=> MSP-3771: Made the knowledge base window always open at the same size and position.

Assets/Scripts/Data Model/PolygonLayer.cs, Assets/Scripts/Interface/PropertiesWindow.cs
=> MSP-3894: Fixed last incorrect area measurement units

Assets/Scripts/Constraints/ConstraintManager.cs, Assets/Scripts/Constraints/RestrictionIssueDeltaSet.cs, Assets/Scripts/Interface/InterfaceCanvas.cs, Assets/Scripts/Interface/Plan Wizard/PlanWizard.cs, Assets/Scripts/Interface/Plans Monitor/Details/PlanDetails.cs, Assets/Scripts/Interface/Time Bar/TimeBar.cs, Assets/Scripts/Issues/IssueManager.cs, Assets/Scripts/Issues/PlanIssueObject.cs
MSP-3893: Added a function to add issues directly to a deltaset if they're new, rather than having to be added to the issuemanager.
MSP-3893: Made the planswizard changes only calculate the issue delta set for submission, without applying them. Also resolved some issues with incorrect issue calculation.
MSP-3893: Cleanup and removal or of an unnecessary constraint check
MSP-3893: Moved the network blocker in front of the planswizard
=> MSP-3893: Reset local client issues if server commit fails

Assets/Scripts/Data Model/LayerManager.cs
=> MSP-3391: Toggling a layer now correctly makes all layer types visible

Assets/Prefabs/Windows/ActivePlanWindow/ActivePlanWindow.prefab
=> MSP-3917: Fixed typos in active plan view mode tooltips

Assets/Plugins/Custom UI/ConfigConverter.cs, Assets/Plugins/Custom UI/ConfigConverter.cs.meta, Assets/Plugins/HEBGraph/Scripts/CurveText.cs, Assets/Plugins/HEBGraph/Scripts/HEBGraph.cs, Assets/Plugins/HEBGraph/Scripts/HEBGraphData.cs, Assets/Plugins/HEBGraph/Scripts/UIRadialDrawer.cs, Assets/Scenes/MSP2050.unity, Assets/Scripts/Data Model/MspGlobalData.cs, Assets/Scripts/Interface/InterfaceCanvas.cs, Assets/Scripts/Interface/Menu Bar/Toggles/Base/MenuBarToggle.cs, Assets/Scripts/Main.cs
MSP-3923: Impact tool config converter and the graph content is now loaded from the config once again
MSP-3923: fixed implementation bugs after testing
MSP-3923: Fixed a small issue with radial drawer inner point closing
=> MSP-3923: Use impact tool config from server config file

Assets/Prefabs/Windows/ImpactTool/ImpactToolWindow.prefab
=> MSP-3944: Impact tool is now properly set to front on click

Assets/Plugins/HEBGraph/Scripts/CurveText.cs
=> MSP-3981: Curved text redraws on enable

Assets/Prefabs/Windows/PlansMonitorWindow/PlansMonitor.prefab, Assets/Scripts/Interface/Plans Monitor/Timeline/PlansTimeline.cs, Assets/Scripts/Interface/Time Bar/TimeBar.cs
=> MSP-3984-3963: timeline overlay now properly blocks, timeview dropdowns properly update on time changes

Assets/Scripts/Data Model/Layer.cs, Assets/Scripts/Interface/Plans Monitor/Details/PlanDetailsTabEnergy.cs
=> MSP-3943: Fixes to energy grid determination and submission

Assets/Scripts/KPI/KPIValue.cs
if we are missing kpi values, use a valid value of a previous month, until it is set
=> handle nullable kpi values

Assets/Scripts/Interface/Options/Options.cs
=> MSP-3791 Release beta10: Added git tag as revision version

Assets/Scripts/Interface/Options/Options.cs
* MSP-3791 Release beta10: Added git tag as revision version
=> MSP-3791 Release beta10: Added git tag as revision version (#71)

Assets/Scenes/LoginScene.unity
=> MSP-3791 Release Beta10

Assets/Scripts/Interface/Options/Options.cs
=> MSP-3791: Release Beta10

Assets/Resources/BuildIdentifier.asset, Assets/Scenes/LoginScene.unity, Assets/Scripts/Interface/Options/Options.cs
=> MSP-3791 Release beta10 with git versioning

Assets/Prefabs/Windows/OptionsWindow/OptionsWindow.prefab
=> MSP-3791/hotfix Changed version inside OptionsWindow prefab

Assets/Scripts/Interface/RoundedImage.cs
=> MSP-2983-fix: Roundedimage now correctly unregisters from size change callback on destroy

Assets/Scripts/Interface/InterfaceCanvas.cs
=> MSP-2983-fix2: Interfacecanvas properly removes itself from instance reference on destroy

Assets/Scenes/NewLoginScene.unity, Assets/Scripts/Interface/LogInMenu/LoginBGMask.cs
=> MSP-4103: login screen bg properly rescales with UI size and resoluti on change

Assets/Resources/Manifest.meta, Assets/Resources/Manifest/UnityManifest.json, Assets/Resources/Manifest/UnityManifest.json.meta, Assets/Scripts/Editor/MSP CI/ProjectBuilder.cs, Assets/Scripts/Interface/LogInMenu/LoginContentTabs/LoginContentTabSessions.cs, Assets/Scripts/Interface/Options/Options.cs, Assets/Scripts/Networking/ServerCommunication.cs, Assets/Scripts/Utility/ApplicationBuildIdentifier.cs, Assets/Scripts/Utility/UnityManifest.cs, Assets/Scripts/Utility/UnityManifest.cs.meta, BuildScripts/CloneSubmodule.bat, BuildScripts/postbuild.sh, BuildScripts/pre_build_task.sh, Jenkinsfile
- [MSP-4276](https://jira.cradle.buas.nl/browse/MSP-4276) Create build job for Unity through Jenkins
- [MSP-4301](https://jira.cradle.buas.nl/browse/MSP-4301) Replace UCB manifest with local manifest
- [MSP-4278](https://jira.cradle.buas.nl/browse/MSP-4278) Include a notification step for the build jobs
- [MSP-4277](https://jira.cradle.buas.nl/browse/MSP-4277) Explore different Jenkins Job behaviour depending on branches
=> MSP-4275: Testing Jenkinsfile automatic build triggering

Jenkinsfile
=> MSP-4397: Better reordering of Nexus repositories, using directories

Jenkinsfile
=> Fixing naming convention for content of zipped build

Jenkinsfile
=> hotfix/MSP-4321: Fixing wrong naming used

Jenkinsfile
=> hotfix/MSP-4321: Removing space in name

Jenkinsfile
=> hotfix/MSP-4321: Removed wrong symbol in path

Jenkinsfile
=> Hotfix/MSP-4321: Setup MSPChallenge-Client to use the new local CI/CD pipeline

Jenkinsfile
=> MSP-4337: Jenkins-GitHub communication

Assets/Scripts/Plans/PlanBackup.cs
=> MSP-4475: Replace our planlayer issues with the ones received from server on submit, but use the right equality comparer

Assets/Scripts/Data Model/GameSession.cs
Removed unused member "game_config_version_id" from GameSession class.
Also fixes crash on loading game session with have value null for game_config_version_id.
=> Removed unused member "game_config_version_id" from GameSession class.

Assets/Scripts/Plans/PlanBackup.cs
=> MSP-4475: new plan issue submission now uses the right callback

Assets/Scripts/Interface/Active Plans Window/ActivePlanWindow.cs
=> MSP-4488: correctly handle APW X when restoring archived plans

Jenkinsfile
=> MSP-4504: Create Nexus Repository to test builds coming from PRs

Assets/Scripts/Data Model/Energy/EnergyLineStringSubEntity.cs, Assets/Scripts/Policies/Energy/PolicyLogicEnergy.cs
=> MSP-4486: Correctly remove old connections when new ones are received

Assets/Prefabs/Windows/OptionsWindow/OptionsWindow_PRFB.prefab, Assets/Scenes/NewLoginScene.unity, Assets/Scripts/Interface/GameSettings.cs, Assets/Scripts/Interface/Generics/GenericWindow.cs, Assets/Scripts/Interface/LogInMenu/LoginBGMask.cs, Assets/Scripts/Interface/Options/Options.cs, Assets/Scripts/Interface/ShowHideManager.cs, ProjectSettings/ProjectSettings.asset
=> MSP-3811: Rescalable windowed mode by default

Assets/Prefabs/Windows/ActivePlanWindowNew/AP_LayerSelectLayer_PRFB.prefab, Assets/Scripts/Interface/Active Plans Window/AP_LayerSelectLayer.cs
=> MSP-3297: added tooltip to Active Plan layer select

Assets/Scripts/Main.cs, Assets/Scripts/Networking/ApiTokenHandler.cs
=> MSP-4532: handling closing the game more properly

Assets/Prefabs/Windows/PropertiesWindow/PropertiesWindowOtherInfo_PRFB.prefab, Assets/Scripts/Interface/Generics/GenericEntry.cs
=> MSP-3816: Make properties window links clickable

Assets/Scenes/MSP2050.unity, Assets/Scripts/Interface/InterfaceCanvas.cs, Assets/Scripts/Interface/Menu Bar/Toggles/Base/MenuBarToggle.cs, Assets/Scripts/Interface/Menu Bar/Toggles/MenuBarLogo.cs
=> MSP-4481-LogoColour: made top left logo button have the current team colour

Assets/Scripts/Drawing Tools/FSM/FSM.cs, Assets/Scripts/Interface/BoxSelect.cs
=> MSP-4531: Box select correctly takes UI scale into account

Assets/Scripts/Interface/GameSettings.cs
=> MSP-4540: impact tool is closed when UI scale or resolution changed

Assets/Prefabs/LoginScreen/LatestNewsEntry_PRFB.prefab, Assets/Prefabs/LoginScreen/LatestNewsSpacer_PRFB.prefab, Assets/Prefabs/LoginScreen/LoginNewsEntry_PRFB.prefab, Assets/Prefabs/LoginScreen/LoginSessionEntry_PRFB.prefab, Assets/Scenes/NewLoginScene.unity, Assets/Scripts/Interface/LogInMenu/LoginContentTabs/LoginContentTabNews.cs, Assets/Scripts/Interface/LogInMenu/LoginNewsEntry.cs
=> MSP-4557: fixes for low resolution login screen scaling

Assets/Prefabs/Generic/GenericHelpWindow_PRFB.prefab, Assets/Prefabs/HelpWindows/SubElements/HelpWindowScrollingText_PRFB.prefab, Assets/Prefabs/Windows/LayerSelectWindow/LayersWindow_PRFB.prefab, Assets/Scenes/MSP2050.unity
=> Small fixes to scene merge and help windows

Assets/Prefabs/Windows/LayerProbeWindow/LayerProbeWindow_PRFB.prefab, Assets/Prefabs/Windows/ObjectivesMonitorWindow/ObjectivesMonitorWindow_PRFB.prefab, Assets/Prefabs/Windows/PropertiesWindow/PropertiesWindow_PRFB.prefab, Assets/Prefabs/Windows/TeamWindow/TeamWindow_PRFB.prefab
=> MSP-4561: UI Polishing for RC2

Assets/Scenes/MSP2050.unity, Assets/Scripts/Interface/Active Plans Window/ActivePlanLayerType.cs, Assets/Scripts/Interface/GameMenu/GameMenu.cs, Assets/Scripts/Interface/Generics/GenericEntry.cs, Assets/Scripts/Interface/Layers/LayerInterface.cs, Assets/Scripts/Interface/Layers/LayerSubCategoryBar.cs
=> MSP-4545: Reset info button callback, close session before returning to login, force close layer window tabs on close

Packages/manifest.json, Packages/packages-lock.json
package update to support the latest rider (c# ide) version
=> updated rider package

Assets/Scripts/Constraints/ConstraintManager.cs, Assets/Scripts/Interface/Active Plans Window/AP_GeometryTool.cs
...As 2-sided constraints were not resolved correctly
=> MSP-4474: Constraint check now always checks the full plan

Assets/Scripts/Interface/Active Plans Window/AP_GeometryTool.cs, Assets/Scripts/Plans/Plan.cs, Assets/Scripts/Policies/Shipping/PolicyLogicShipping.cs
(and doesn't immediately start again). 
Also includes a small fix for MSP-4539
=> MSP-4473: Correctly redraw layers when editing stops

Assets/Prefabs/Tutorial/TutorialUI_PRFB.prefab, Assets/Resources/MainTutorialData.asset, Assets/Scripts/Interface/Tutorial/ATutorialDataStep.cs, Assets/Scripts/Interface/Tutorial/TutorialDataStepDiverging.cs, Assets/Scripts/Interface/Tutorial/TutorialDataStepRegular.cs, Assets/Scripts/Interface/Tutorial/TutorialDataStepTitle.cs, Assets/Scripts/Interface/Tutorial/TutorialDataStepTitleChoice.cs, Assets/Scripts/Interface/Tutorial/TutorialManager.cs, Assets/Scripts/Interface/Tutorial/TutorialUI.cs
=> MSP-4611: tutorial chapter navigation and close button

Assets/Prefabs/Tutorial/TutorialUI_PRFB.prefab, Assets/Prefabs/Windows/ActivePlanWindowNew/AP_ApprovalEntry_PRFB.prefab, Assets/Resources/MainTutorialData.asset, Assets/Scripts/Drawing Tools/FSM/EditLineStringsState.cs, Assets/Scripts/Drawing Tools/FSM/EditPointsState.cs, Assets/Scripts/Drawing Tools/FSM/EditPolygonsState.cs, Assets/Scripts/Drawing Tools/FSM/FSMState.cs, Assets/Scripts/Interface/Tutorial/TutorialManager.cs, Assets/Scripts/Interface/Tutorial/TutorialRequirements/TutorialRequirementGeometrySelected.cs, Assets/Scripts/Interface/Tutorial/TutorialRequirements/TutorialRequirementGeometrySelected.cs.meta
=> Msp 4612: Tutorial chapter III changes

Assets/Scripts/Interface/Active Plans Window/AP_Communication.cs, Assets/Scripts/Interface/Active Plans Window/ActivePlanWindow.cs
=> MSP-4559: Two plan message minor issues

Assets/Prefabs/Windows/OptionsWindow/OptionsEntryText_PRFB.prefab, Assets/Scripts/Data Model/LayerManager.cs
=> MSP-4541: options window text no longer overflows

Assets/Prefabs/Windows/TeamWindow/TeamWindow_PRFB.prefab, Assets/Scripts/Interface/Layout/SetLayoutToPrefHeight.cs
=> MSP-4575: Teams window now sets its own min height

Assets/Scripts/Interface/Active Plans Window/ActivePlanWindow.cs, Assets/Scripts/Interface/PlansTimeline/PlansTimeline.cs
=> MSP-4574: avoid plans being added to objectives monitor twice

Assets/Prefabs/Generic/GenericHelpWindow_PRFB.prefab, Assets/Prefabs/HelpWindows/ObjectivesMonitor_Default_HelpWindow_PRFB.prefab, Assets/Prefabs/HelpWindows/ObjectivesMonitor_Geometry_HelpWindow_PRFB.prefab, Assets/Prefabs/HelpWindows/ObjectivesMonitor_KPI_HelpWindow_PRFB.prefab, Assets/Prefabs/HelpWindows/ObjectivesMonitor_Parent_HelpWindow_PRFB.prefab
=> MSP-4647: Anchors fix for HelpWindows

SonarQube/Jenkinsfile
=> MSP-4634: SonarQube Integration

Assets/Prefabs/Windows/ActivePlanWindowNew/AP_Communication_PRFB.prefab, Assets/Prefabs/Windows/ActivePlanWindowNew/ActivePlanWindowNew_PRFB.prefab, Assets/Prefabs/Windows/NotificationWindow/NotificationEntry_PRFB.prefab, Assets/Scripts/Interface/Active Plans Window/AP_Communication.cs, Assets/Scripts/Interface/Active Plans Window/AP_CommunicationMessage.cs, Assets/Scripts/Interface/Distribution Elements/DistributionSlider.cs, Assets/Scripts/Interface/Layout/SetLayoutToPrefHeight.cs, Assets/Scripts/Interface/PlansList/PlanBar.cs, Assets/Scripts/Interface/PlansList/PlansList.cs, Assets/Scripts/Networking/ServerCommunication.cs, Assets/Scripts/Plans/Plan.cs, Assets/Scripts/Policies/Energy/PolicyLogicEnergy.cs, Assets/Scripts/Policies/Fishing/PolicyLogicFishing.cs
=> MSP-RC3PlayTestFix: resolves issues 4636, 4641, 4646, 4616, 4640, 4642, 4640, 4643, 4644, 4645

SonarQube/Jenkinsfile
=> MSP-4634: Fixing SonarQube Jenkinsfile

SonarQube/Jenkinsfile
=> MSP-4634: Enclosing declaration in script block

SonarQube/Jenkinsfile
=> MSP-4634: extended script enclosure

.gitignore, MSP2050.csproj, MSPChallenge-Client.sln
=> MSP-4634: removed main .sln and .csproj files for SonarQube

.gitignore
=> MSP-4634: Removed .sln from repository

MSP2050.csproj
=> MSP-4634: Updated MSP2050.csproj

MSP2050.csproj
=> MSP-4634: Changed C# version to 8.0

Assets/Scripts/Camera/CameraZoom.cs, Assets/Scripts/Interface/Tooltip/AddTooltip.cs
=> MSP-4634: Removed instructions incompatible with C# 7.3

SonarQube/Jenkinsfile
=> MSP-4634: Targeting .sln file for msbuild

SonarQube/Jenkinsfile
=> MSP-4634-hotfix-XII

MSP2050.csproj
=> MSP-4634: Upgrading MSP2050.csproj C# version to 8.0

Assets/Scripts/Data Model/MspGlobalData.cs, Assets/Scripts/Interface/TeamWindow.cs
=> MSP-4630: rename region_base_url  and check for trailing '/'

Assets/Scripts/Interface/LogInMenu/LoginNewsEntry.cs
=> MSP-4545: (Client, macOS only) Clicking on Read More under News in main/opening screen does not work

Assets/Scripts/Interface/Active Plans Window/AP_Communication.cs, Assets/Scripts/Interface/Active Plans Window/ActivePlanWindow.cs
=> MSP-4681: fix nullref on invalid message header update

Jenkinsfile
=> MSP-4689: Refactor of Jenkinsfile indentation for better readability

Assets/Scripts/Data Model/Ecology/FishingDistributionSet.cs, Assets/Scripts/Interface/Distribution Elements/KPIOtherValueArea.cs
added better error handling on initial fishing values . Client crashed before. In debug you get an readbable error log
see screenshot
=> Added better error handling on initial fishing values . Client crashed before.

Jenkinsfile
=> MSP-4960: Implementing Discord notifications for Jenkins jobs

Jenkinsfile
=> MSP-4960-hotfix

Assets/Resources/MainTutorialData.asset, Assets/Scripts/Camera/CameraManager.cs, Assets/Scripts/Data Model/MspGlobalData.cs, Assets/Scripts/Interface/Tutorial/TutorialManager.cs, Assets/Scripts/Main.cs
=> MSP 4768 4924 4776 4942

Jenkinsfile
=> MSP-5179: Adapt Jenkinsfile to the new network

Assets/Scripts/Data Model/LayerInfo.cs
Added in position 3 PitExtractionDepth inside the enum in Assets/Scripts/Data Model/LayerInfo.cs (CLIENT)
=> MSP-5207: Pit extraction depth parameter

Jenkinsfile
Checklist before requesting a review
[ N/A ] I am using the Jira issue number in the commit message.
[ N/A ] The branch is named as the Jira issue number.
Replacement of old Jenkins pipeline with new Jenkins (Docker) Pipeline into dev branch
(will need to propagate to other branches for Jenkins Multibranch to be fully ready)
=> Replace Jenkins Pipeline

SonarQube/Jenkinsfile
=> Update SonarQube Jenkinsfile

Jenkinsfile
=> Fix Multibranch to actually be multibranch

Jenkinsfile
=> Move hardcoded values into config variables

Assets/Scripts/Data Model/LayerInfo.cs, Assets/Scripts/Data Model/PolygonLayer.cs
=> MSP-5295-hotfix: Temporary change way of displaying surface km text

Assets/Scenes/NewLoginScene.unity
=> MSP-5445: fixed missing texture assignment in login scene

Assets/Scripts/Interface/Dashboard/DashboardManager.cs
=> Main to dev

Assets/Prefabs/Windows/ActivePlanWindowNew/ActivePlanWindowNew_PRFB.prefab, Assets/Resources/MainTutorialData.asset, Assets/Scenes/MSP2050.unity, Assets/Scripts/Data Model/LayerManager.cs, Assets/Scripts/Interface/Active Plans Window/ActivePlanWindow.cs, Assets/Scripts/Interface/InterfaceCanvas.cs, Assets/Scripts/Interface/Map Scale/MapScale.cs, Assets/Scripts/Interface/ShowHideManager.cs, Assets/Scripts/Interface/Tutorial/TutorialActions/TutorialActionSetAPButtonCover.cs, Assets/Scripts/Interface/Tutorial/TutorialActions/TutorialActionSetAPButtonCover.cs.meta, Assets/Scripts/Interface/Tutorial/TutorialActions/TutorialActionSetLayersToBase.cs, Assets/Scripts/Interface/Tutorial/TutorialActions/TutorialActionSetLayersToBase.cs.meta, Assets/Scripts/Interface/Tutorial/TutorialDataStepTitle.cs, Assets/Scripts/Interface/Tutorial/TutorialDataStepTitleChoice.cs, Assets/Scripts/Interface/Tutorial/TutorialManager.cs
=> MSP-4777: All tutorial improvements mentioned in tasks 4777, 4779 and 4892

Assets/Scripts/Data Model/AbstractLayer.cs
=> MSP-5446: No longer assume protection layers are multitype

Assets/Scripts/Data Model/Layer.cs
=> MSP-5511: Make sure new planlayers are sorted behind existing planlayers at the same implementation time

Assets/Resources/Dashboard/Widgets/SunHoursWidget_PRFB.prefab, Assets/Scripts/Interface/Dashboard/ADashboardWidget.cs
=> MSP-5521: Remove editor ref, remove focus select from sunhour widget

Assets/Resources/Data Visualization Settings.asset, Assets/Scripts/Data Model/LayerManager.cs, Assets/Scripts/Data Model/LineStringSubEntity.cs, Assets/Scripts/Data Model/PolygonSubEntity.cs
=> MSP-5561: Resolved issues preventing NMC from loading

Assets/Scripts/Interface/LogInMenu/LoginManager.cs, Assets/Scripts/Networking/ServerCommunication.cs
=> MSP-5582: Reset token handler when (re)entering the login scene

Assets/Scripts/Data Model/PolygonSubEntity.cs
=> MSP-5575: Disabled polygon LOD simplification. They were not properlyused and caused triangulation errors.

Assets/Scripts/Data Model/PolygonSubEntity.cs
This reverts commit 8d047b29a75a742f6e2f05c8a2ddcd72a44d8378.
=> MSP-5617: Release 5.1.0 Hotfix

Assets/Scripts/Data Model/PolygonSubEntity.cs
=> MSP-5641: Disable polygon LOD simplification again

Assets/Scripts/Drawing Tools/FSM/CreatePointsState.cs, Assets/Scripts/Drawing Tools/FSM/CreatingLineStringState.cs, Assets/Scripts/Drawing Tools/FSM/CreatingPolygonState.cs, Assets/Scripts/Drawing Tools/FSM/EditPointsState.cs, Assets/Scripts/Drawing Tools/FSM/Energy/CreateEnergyPointState.cs, Assets/Scripts/Drawing Tools/FSM/Energy/CreatingEnergyLineStringState.cs, Assets/Scripts/Drawing Tools/FSM/Energy/EditEnergyPointsState.cs
=> MSP-1078: Select geometry after creating it

Assets/Scripts/Interface/Dashboard/DashboardManager.cs
=> MSP-852: Fix dashboard crash on fav widget removal

Assets/Scripts/Policies/Fishing/PolicyLogicFishing.cs
=> MSP-1179: Dont use fishing effort from archived plans as reference

Assets/Prefabs/Windows/Dashboard/Graphs/GraphContentSelectToggle_PRFB.prefab, Assets/Resources/Dashboard/Widgets/BiodiversityWidget_PRFB.prefab, Assets/Resources/Dashboard/Widgets/BiomassWidget_PRFB.prefab, Assets/Resources/Dashboard/Widgets/BycatchWidget_PRFB.prefab, Assets/Resources/Dashboard/Widgets/CatchPerGearTypeWidget_PRFB.prefab, Assets/Resources/Dashboard/Widgets/CatchPerSpeciesWidget_PRFB.prefab, Assets/Resources/Dashboard/Widgets/CatchVersusBiomassPerSpeciesWidget_PRFB.prefab, Assets/Resources/Dashboard/Widgets/EnergyAreaWidget_PRFB.prefab, Assets/Resources/Dashboard/Widgets/EnergyInvestmentWidget_PRFB.prefab, Assets/Resources/Dashboard/Widgets/EnergyProductionWidget_PRFB.prefab, Assets/Resources/Dashboard/Widgets/EnergySharedWidget_PRFB.prefab, Assets/Resources/Dashboard/Widgets/EnergyUsedWidget_PRFB.prefab, Assets/Resources/Dashboard/Widgets/EnergyWastedWidget_PRFB.prefab, Assets/Resources/Dashboard/Widgets/ProtectionAreaWidget_PRFB.prefab, Assets/Resources/Dashboard/Widgets/RytherIndexWidget_PRFB.prefab, Assets/Resources/Dashboard/Widgets/ShippingEfficiencyWidget_PRFB.prefab, Assets/Resources/Dashboard/Widgets/ShippingGeneralWidget_PRFB.prefab, Assets/Resources/Dashboard/Widgets/ShippingIncomeWidget_PRFB.prefab, Assets/Scripts/Interface/Dashboard/ContentSelect/AGraphContentSelect.cs, Assets/Scripts/Interface/Dashboard/ContentSelect/GraphContentSelectFixedCategory.cs, Assets/Scripts/Interface/Dashboard/Legend/GraphLegend.cs, Assets/Scripts/Policies/SandExtraction/PolicyLogicSandExtraction.cs
=> MSP-1136: dashboard legend shows country name

Assets/Scripts/Interface/Dashboard/Legend/GraphLegend.cs
=> MSP-1225: Fixed graph legend coroutine while disabled bug
